# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: unityci/editor:ubuntu-2021.3.4f1-webgl-1.0.1

pipelines:
  custom:
    GetActivationFile:
    - step:
        name: 'Get Activation File'
        script:
          - chmod +x ./ci/get_activation_file.sh && ./ci/get_activation_file.sh
        artifacts:
          - unity3d.alf
  
#  default: 
#   - step:
#       name: 'Run Test in Edit Mode and Play Mode'
#        size: 2x
#        caches:
#          - linux-library
#        script:
#          - chmod +x ./ci/activate.sh && ./ci/activate.sh
#          - export TEST_PLATFORM=PlayMode
#          - chmod +x ./ci/test.sh && ./ci/test.sh

#    - parallel:
    BuildScorm:
      - step:
          name: 'Build WebGL + SCORM'
#          runs-on:
#            - self.hosted
#            - linux
          size: 2x
          image: unityci/editor:ubuntu-2021.3.4f1-webgl-1.0.1
          caches:
            - linux-library
          script:
            - echo $UNITY_LICENSE_FILE_B64 | tr -d '[:space:]' | sed 's/.\{64\}/&\n/g' | base64 -d > $UNITY_LICENSE_FILE
            - chmod +x ./ci/activate.sh && ./ci/activate.sh
            - export BUILD_TARGET=WebGL
            - export CUSTOM_BUILD_TARGET=SCORM
            - chmod +x ./ci/build.sh && ./ci/build.sh
          artifacts:
            - Builds/*.zip
    
    BuildWindows:
      - step:
          name: 'Build Windows Standalone'
          size: 2x
          image: unityci/editor:ubuntu-2021.3.4f1-windows-mono-1.0.1
          caches:
            - windows-library
          script:
            - echo $UNITY_LICENSE_FILE_B64 | tr -d '[:space:]' | sed 's/.\{64\}/&\n/g' | base64 -d > $UNITY_LICENSE_FILE
            - chmod +x ./ci/activate.sh && ./ci/activate.sh
            - export BUILD_TARGET=StandaloneWindows64
            - export CUSTOM_BUILD_TARGET=StandaloneWindows64
            - chmod +x ./ci/build.sh && ./ci/build.sh
          artifacts:
            - Builds/**
            
    ActivateUnityLicense:
      - step:
          name: 'Activate Unity License'
          script:
            - echo $UNITY_LICENSE_FILE_B64 | tr -d '[:space:]' | sed 's/.\{64\}/&\n/g' | base64 -d > $UNITY_LICENSE_FILE
            - chmod +x ./ci/activate.sh && ./ci/activate.sh

            
definitions:
  caches:
    linux-library: Library
    windows-library: Library